### PR TITLE
Fixing an issue where the Win32 content prep tool crashes

### PR DESCRIPTION
**Pull request by nikyusof**
- Updating the binaries with the fixes where the Win32 content prep tool crashes.

### CODE REVIEW

**Comment by EdijsPerkums** [comment]
@nikyusof #123  is not fixed. I can create two packages with the following command on Windows 11 terminal Command Prompt:
"C:\Users\USER\Downloads\IntuneWinAppUtil.exe" -c "C:\Users\USER\Desktop\Test" -s Deploy-Application.exe -o "C:\Users\USER\Desktop" -q
then on the third time terminal crashes and no package is created.
If I reopen terminal, then I cannot create another package. Terminal crashes on first try. 
If I run this command:
"C:\Users\USER\Downloads\IntuneWinAppUtil.exe" /? 
That just displays the help information then I can create 2 packages again and on the third try I get the same crash.
I have verified this multiple times. If I maximize the terminal then it still works.

Event viewer info:
Faulting application name: IntuneWinAppUtil.exe, version: 6.2404.13.0, time stamp: 0xa9f45829
Faulting module name: KERNELBASE.dll, version: 10.0.26002.1000, time stamp: 0x13647ec8
Exception code: 0xe0434352
Fault offset: 0x0000000000019389
Faulting process id: 0x7F0
Faulting application start time: 0x1DA6A6DEAEC3BF7

**Comment by nikyusof** [comment]
@EdijsPerkums do you have anymore information about the actual error that happened? Is the error the same as the first screenshot in #123 ?

**Comment by EdijsPerkums** [comment]
@nikyusof I have updated my post with a video. Do you need more information? It is a clean new windows 11 vm. Happens also on my work pc, not just the vm.

**Comment by auriuman78** [comment]
wanted to add a note, I was using this version without issues about a month ago, wrapped up several intune win32 packages without issue.  Today went to do it and got all of the above noted symptoms.  Not sure if that's helpful at this point but thought I'd mention this - same version running on same computer but have updated windows since the work.

**Pull request merged**
