### PR TITLE
Fixing crash issue with Win32 content prep tool

### LINKED ISSUE #108: IntuneWinAppUtil.exe crashes the whole terminal without any error message displayed
Hi,

I'm trying to package Git for deployment via Intune, but the packaging of the installer fails. It completely crashes the terminal, and no error message is displayed (or I don't have the time to notice it before the terminal crashes.

Installer I'm trying to package : https://github.com/git-for-windows/git/releases/download/v2.42.0.windows.2/Git-2.42.0.2-64-bit.exe
Command-line used : .\IntuneWinAppUtil.exe -c "C:\Users\XXX\Downloads\IntuneWinAppUtil\Git\" -s "Git-64-bit.exe" -o "C:\Users\XXX\Downloads\IntuneWinAppUtil\out\"

It worked fine for the previous version of the Git installer :-/ 

I tried in Powershell 7.3.8, and a Command Prompt

### PR DESCRIPTION
**Pull request by nikyusof**
- Updating the binaries that fixes the issue with Win32 content prep tool crashing.
- Fixes #108

### CODE REVIEW

**Comment by scidonem** [comment]
This has broken the tool for me, causing it to crash with the below:

`INFO   Validating parameters
INFO   Validated parameters within 2 milliseconds
INFO   Removing temporary files
ERROR  System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int[32](https://github.com/fmgl/mwrk-apps-repository/actions/runs/6739317142/job/18321202678#step:7:33) errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.PrintProgress(AppContext context)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)`

**Comment by nikyusof** [comment]
@scidonem would you mind providing these:
- OS version.
- Command line platform (Powershell, CMD, etc.). Provide version as well.
- Command that you ran that encountered this error.

Can you also try the same command on the previous version to see if you are getting the same error or not?

**Comment by githubpow** [comment]
Hello @nikyusof 

With new tool version or the last version, the tool crashes even though I do .\IntuneWinAppUtil.exe -h

OS version: Win11 22H2 (OS build 22621.2506)
Command line platform: Powershell 5.1 build 22621 rev 2506
crashing command lines:
.\IntuneWinAppUtil.exe -h
.\IntuneWinAppUtil.exe -c .\source\ -s .\source\xxx.exe -o .\output\

My workaround is still open the Powershell console maximized

**Comment by hh-trj** [comment]
@nikyusof It's crashing for me, as well. The previous version is also crashing. Having PowerShell maximized fixes the issue.

OS version - Windows 11 23H2 (22631.2428)
Command line platform (Powershell, CMD, etc.). Provide version as well - PowerShell 5.1.22621.2428
Command that you ran that encountered this error:

`& "$($env:USERPROFILE)\IntuneWinAppUtil.exe" -c "$($env:USERPROFILE)\source\repos\intunewin-microsoft-winget\src" -s "Install-App.ps1" -o "$($env:USERPROFILE)\source\repos\intunewin-microsoft-winget\dist"`

**Comment by Joly0** [comment]
For me this is working, but why wasnt there a new release or anything? The Binary go swapped, but nothing else. No additional information or anything?

**Comment by scidonem** [comment]
> @scidonem would you mind providing these:
> 
> * OS version.
> * Command line platform (Powershell, CMD, etc.). Provide version as well.
> * Command that you ran that encountered this error.
> 
> Can you also try the same command on the previous version to see if you are getting the same error or not?

OS version Windows Server 2022
Running in PowerShell via WinRM with no GUI (runs as part of GitHub workflow)


Command runs fine in previous version so have pinned that version in the workflow for now.

```
              ."${{ github.workspace }}/intune/util/Microsoft-Win32-Content-Prep-Tool/IntuneWinAppUtil.exe" -q -c "$($_.FullName)" -s "Deploy-Application.exe" -o "${{ github.workspace }}/intune/output"
```

**Comment by DanoThom** [comment]
This change has caused the prep tool to fail for me in Azure DevOps pipelines in a powershell task with the same 'handle' error:
`ERROR  System.IO.IOException: The handle is invalid`

Anyone aware of a workaround for this in a similar headless environment?

**Comment by scidonem** [comment]
Yes. use the previous version
Same problem here in a GitHub pipeline. That'll teach me for checkout the latest source every time and not pinning a release tag 😃

________________________________

**Comment by stutf** [comment]
I also confirm this bug - mine always crashed at 61 or 62 percent.
I tried both v1.8.4 and v1.8.5 with same issue.
I tried both Powershell and CMD with same issue, both inside the 'Windows Terminal'
Maximizing the window fixes the crash in both Powershell and CMD, both inside 'Windows Terminal'
I'm running W11 23H2.

**Comment by MattKeenSA** [comment]
> Maximizing the window fixes the crash in both Powershell and CMD, both inside 'Windows Terminal' I'm running W11 23H2.

I can confirm this works for me too, Maximised Terminal/CMD window allow the process to run and create the package.

**Pull request merged**
